contact_links:
  - name: Feature Request
    url: https://github.com/Authenticator-Extension/Authenticator/discussions/new
    about: Please request features here.
  - name: Translation Issues
    url: https://crowdin.com/project/authenticator-firefox
    about: Please correct translation issues on Crowdin.
